version: '3'
services:
  pokedexApp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexApp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./docker/mongo:/data/db